name: Makefile CI

on:
  push:
    branches: [ "vercel" ]
  pull_request:
    branches: [ "vercel" ]

jobs:
  build:
    runs-on: ubuntu-latest  # Gunakan `ubuntu-latest` atau runner Linux

    steps:

      - name: Install dependencies
        run: make

      - name: Run check
        run: make check

      - name: Run distcheck
        run: make distcheck
